# Generated by Django 5.2.6 on 2025-10-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=100)),
                ('p_artist', models.CharField(max_length=50)),
                ('p_desc', models.CharField(max_length=500)),
                ('p_dims', models.CharField(max_length=500)),
                ('p_price', models.CharField(max_length=100)),
            ],
        ),
    ]
