# Generated by Django 5.2.7 on 2025-10-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting_detail',
            name='p_image_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
