# Generated by Django 5.2.7 on 2025-10-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cartitem_delete_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='painting',
            new_name='product',
        ),
    ]
