# Generated by Django 5.2.7 on 2025-10-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_painting_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='painting',
        ),
    ]
