# Generated by Django 3.1.12 on 2025-11-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20251104_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='painting',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='painting_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='painting_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='painting_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Painting_detail',
        ),
    ]
