# Generated by Django 3.1.12 on 2026-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20260804_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
